<a href="https://colab.research.google.com/github/Keshabbu/Datascience/blob/main/Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Classification --> Supervised ML

Output -> Categorical

2 Categories --> Yes/No

1000 Datapoints in dataset

900 Yes and 100 No

- 900 : 100 -> 9 : 1 [Imbalanced Dataset]
- 500 : 500 -> 1 : 1 [Balanced Dataset]
- 600 : 400 -> 6 : 4 [Balanced Dataset]
- 700 : 300 -> 7 : 3 [Can be imbalanced or balanced according to the condition]

Techniques to handle imbalanced dataset
- Upsampling
- Downsampling

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
n_class_0 = 900
n_class_1 = 100

In [ ]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(0, 1, 900),
    'feature_2': np.random.normal(0, 1, 900),
    'target': [0]*900
})

In [ ]:
class_0

     feature_1  feature_2  target
0     0.690675  -0.115631       0
1     0.872622  -0.898911       0
2     0.921776   1.843134       0
3     0.120217   0.942241       0
4     0.617197  -0.659779       0
..         ...        ...     ...
895  -0.158163   0.592495       0
896   0.237526  -0.076373       0
897  -0.810837  -0.013812       0
898   0.036829  -0.121343       0
899  -1.748913  -0.998172       0

[900 rows x 3 columns]

In [ ]:
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(2, 1, 100),
    'feature_2': np.random.normal(2, 1, 100),
    'target': [1]*100
})

In [ ]:
class_1

    feature_1  feature_2  target
0    2.938587   1.489803       1
1    2.078456   0.715132       1
2    1.206347  -0.083523       1
3    2.994472   3.448211       1
4    3.179039   2.618054       1
..        ...        ...     ...
95   3.435868   1.276055       1
96   1.336504   3.181924       1
97   3.390756   0.946159       1
98   0.183584   1.432510       1
99   2.835837   0.676342       1

[100 rows x 3 columns]

In [ ]:
class_0.shape, class_1.shape

((900, 3), (100, 3))

In [ ]:
df = pd.concat([class_0, class_1]).reset_index(drop = True)

In [ ]:
df.head()

   feature_1  feature_2  target
0   0.690675  -0.115631       0
1   0.872622  -0.898911       0
2   0.921776   1.843134       0
3   0.120217   0.942241       0
4   0.617197  -0.659779       0

In [ ]:
df.shape

(1000, 3)

In [ ]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

Upsamping

In [ ]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [ ]:
df_majority.shape, df_minority.shape

((900, 3), (100, 3))

In [ ]:
from sklearn.utils import resample

df_minority_upsampled = resample(df_minority, replace = True, n_samples = len(df_majority))

In [ ]:
df_minority_upsampled.shape

(900, 3)

In [ ]:
df_majority_downsampled = resample(df_majority, replace = False, n_samples = len(df_minority))

In [ ]:
df_majority_downsampled.shape

(100, 3)